export const CREATE_BOARD_ERROR = 'CREATE_BOARD_ERROR';
export const CREATE_BOARD_SUCCESS = 'CREATE_BOARD_SUCCESS';

export const READ_BOARD_ERROR = 'READ_BOARD_ERROR';
export const READ_BOARD_SUCCESS = 'READ_BOARD_SUCCESS';

export const UPDATE_BOARD_ERROR = 'UPDATE_BOARD_ERROR';
export const UPDATE_BOARD_SUCCESS = 'UPDATE_BOARD_SUCCESS';

export const DELETE_BOARD_ERROR = 'DELETE_BOARD_ERROR';
export const DELETE_BOARD_SUCCESS = 'DELETE_BOARD_SUCCESS';
