swagger: '2.0'
info:
  version: 1.0.0
  title: Message API
  description: Message API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
host: localhost:3000
basePath: "/api"
tags:
- name: Message
  description: API for Message in the system
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  "/message":
    get:
      tags:
      - Message
      summary: Get all messages in the system
      responses:
        '200':
          description: OK
          schema:
        '500':
          description : Could not retrieve all messages
    post:
      tags:
      - Message
      summary: Add a new Message in the system
      parameters:
      - name: message
        in: body
        description: Message that we want to create
        schema:
          "$ref": "#/definitions/Message"
      produces:
      - application/json
      responses:
        '200':
          description: New Message is created
        '400':
          description : text not found
        '500':
          description : Could not created Message
  "/message/{messageId}":
    parameters:
    - name: messageId
      in: path
      required: true
      description: ID of Message that we want to find
      type: string
    get:
      tags:
      - Message
      summary: Get Message with given ID
      responses:
        '200':
          description: Message is found
        '500':
          description: Could not retrieve this message id
    put:
      summary: Update Message with given ID
      tags:
      - Message
      parameters:
      - name: message
        in: body
        description: Message with new values of properties
        schema:
          "$ref": "#/definitions/Message"
      responses:
        '200':
          description: Message is updated
        '400':
          description : messageId not found
        '401':
          description : text not found
        '500':
          description : Could not update this message id    
    delete:
      summary: Delete Message with given ID
      tags:
      - Message
      responses:
        '200':
          description: Message is deleted
        '400':
          description : The id can not be empty
        '500':
          description : Could not delete this message id

definitions:
  Message:
    required:
    - text
    properties:
      text:
        type: string
